### ISSUE TITLE
Gem doesn't work in Chrome 70.0.3538.77

### ISSUE THREAD

**Issue by anaharris** [nbulaj/mapbox-gl-rails#3]
This gem doesn't seem to work on Chrome 70.0.3538.77. This is code from our template. We see the alert box pop up. It works in Safari and Firefox.

```
  if (!mapboxgl.supported()) {
    alert('Your browser does not support Mapbox GL');
  } else {
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v9',
        center: [<%= @post.longitude %>, <%= @post.latitude %>],
        zoom: 15
    });
  }
```

**Comment by nbulaj** [comment]
Hi @anaharris . Don't sure this is a problem of gem, because it's just includes Mapbox GL assets. Maybe you need to report your issue in Mapbox repo ? https://github.com/mapbox/mapbox-gl-js

Also check rendered template for the JS/CSS files of Mapbox and check it's version.
