### ISSUE TITLE
Update docs to include instructions for Rails 6 app

### ISSUE THREAD

**Issue by djrobby** [nbulaj/mapbox-gl-rails#4]
Can you update docs to include instructions on how to require JS inside a Rails 6 app using webpack?

**Comment by nbulaj** [comment]
Hi @djrobby . Actually, this gem provides Mapbox GL JS for sprockets asset pipeline. If you are planning top use webpack / webpacker, than you can just simply add `mapbox-gl-js` to your dependencies using webpack

https://stackoverflow.com/questions/50423419/using-mapbox-gl-and-mapbox-mapbox-gl-draw-with-webpack

**Comment by djrobby** [comment]
Thank you! That solves my issue.
