### ISSUE TITLE
Upgrade to 1.9.1

### ISSUE THREAD

**Issue by waissbluth** [nbulaj/mapbox-gl-rails#6]
Hello,

I am looking for version 1.9.1, which is not yet available. I am willing to open a PR with this change, but the process to do so seems not to be documented anywhere. What is the recommended source to grab the js and scss files?

The file at https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl-dev.js seems to be a good starting point, but I have not found the companion scss in non-minified format.

Thanks!

**Comment by nbulaj** [comment]
Whoops, sorry @waissbluth , I've already pushed it to rubygems :( 

And seems like I need to add upgrade / release notes. Thanks for a ping!
