### ISSUE TITLE
Upgrade to Mapbox GL 2.9.0; globe view projection not working

### ISSUE THREAD

**Issue by rudokemper** [nbulaj/mapbox-gl-rails#7]
Currently, when you create a new map in Mapbox Studio, the default projection is the new `globe` view. This rather new projection was not yet supported by Mapbox GL 2.7.0, and so when a user tries to load a new Mapbox Studio map with `mapbox-gl-rails`, it does not work until the user changes the projection from Studio into one of the other options. Or, alternatively, we have to build some validation code into our Rails app to handle  any incoming `projection: globe` maps to load with one of the other projections e.g. mercator instead.

I think it should be straightforward to bump the version to 2.9.0 in `mapbox-gl.js` for this gem.

**Comment by nbulaj** [comment]
Done @rudokemper , thanks

**Comment by rudokemper** [comment]
That's great, @nbulaj! Thank you. Now just to figure out how to get this latest version (with newly introduced `rgb(x x x / x%)` css standards) to play nicely with sassc-ruby.. but that's an issue with sass, not your gem 🙂
